version: '3'

networks:
  testnet:
    driver: bridge

services:
  # Starts the go-ethereum client with the genesis configuration.
  geth:
    container_name: geth
    image: ethereum/client-go:latest
    user: $UID:$GID
    command:
      - --datadir=/execution
      - --networkid=31337
      - --unlock=0000000c31f7b3221f7e405c8e735abd3b10a78d
      - --password=/execution/password.txt
      - --allow-insecure-unlock
      - --nodiscover
      - --syncmode=full
      - --authrpc.addr=localhost
      - --authrpc.port=8551
      - --authrpc.vhosts=localhost
      - --http
      - --http.addr=0.0.0.0
      - --http.api=engine,eth,web3,net,debug,flashbots,builder,txpool
      - --http.corsdomain=*
      - --http.port=8545
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.port=8546
      - --verbosity=3
      - --mine
      - --miner.threads=1
      - --miner.etherbase=0000000c31f7b3221f7e405c8e735abd3b10a78d
      - --metrics
      - --metrics.addr=0.0.0.0
    volumes:
      - ./execution:/execution
    environment:
      - GID
      - UID
    ports:
      - 6060:6060
      - 8545:8545
      - 8546:8546
      - 8551:8551
      - 30303:30303
    networks:
      - testnet
